apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  name: ace-designer
spec:
  couchdb:
    replicas: 1
    storage:
      class: ibmc-block-gold
      size: 10Gi
      type: persistent-claim
  designerFlowsOperationMode: local
  designerMappingAssist:
    enabled: true
    incrementalLearning:
      schedule: Every 15 days
  license:
    accept: true
    license: L-APEH-C9NCK6
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  useCommonServices: true
  version: 12.0.4
