#  Before running this with the oc command, 
# 1. create a namespace you want to use "oc new-namespace name"
# 2. get the entitlement key https://myibm.ibm.com/products-services/containerlibrary
# 3. update OCP with the userid and entitlement key using the command "oc create secret docker-registry ibm-entitlement-key --docker-server=cp.icr.io --docker-username=cp --docker-password=ENTITLEMENT_KEY --docker-email=OCP_LOGIN_CREDENTIALS"
# 4.  Apply this with "oc apply -f install cp4i.yaml" after updating the NAMESPACE variables below

# IBM Common Services Operator Catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-common-service-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM Operator Catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-operator-catalog 
  publisher: IBM Content
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
---
# Creates the necessary security for the Operator under the mq namespace
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibmmq-operator
  namespace: [NAMESPACE]
spec:
  targetNamespaces:
  - [NAMESPACE]
---
# install CP4I and all applications
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp-integration
  namespace: [NAMESPACE]
spec:
  channel: latest
  installPlanApproval: Automatic
  name: ibm-cp-integration
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
