kind: ConfigMap
apiVersion: v1
metadata:
  name: mq-mqsc-qm1
  namespace: [NAMESPACE]
data:
  mqsc: |
    DEFINE QLOCAL(IN.Q) DEFPSIST(YES)
    DEFINE QLOCAL(OUT.Q) DEFPSIST(YES)
    DEFINE CHANNEL(EXTERNAL.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    SET CHLAUTH(EXTERNAL.SVRCONN) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
