# IBM Common Services Operator Catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBMCS Operators
  publisher: IBM
  sourceType: grpc
  image: docker.io/ibmcom/ibm-common-service-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m

# ---------------------------------------- #

# IBM Operator Catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-operator-catalog 
  publisher: IBM Content
  sourceType: grpc
  image: docker.io/ibmcom/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m

# ---------------------------------------- #

# Creates the necessary security for the Operator under the mq namespace
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibmmq-operator
  namespace: [NAMESPACE]
spec:
  targetNamespaces:
  - [NAMESPACE]

# ---------------------------------------- #

# Install the MQ Operator in All Namespaces
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: openshift-operators
spec:
  channel: v1.5
  name: ibm-mq
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
