kind: Secret
apiVersion: v1
metadata:
  name: mq-tls-key-{{- .Values.queuemanager.name | lower}}
data:
  tls.key: {{- .Values.certificates.key | indent 1}}
  tls.crt: {{- .Values.certificates.crt | indent 1}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: mq-tls-trust-{{- .Values.queuemanager.name | lower}}
data:
  {{- range $i, $item := .Values.trust.certs}}
  tls{{$i}}.crt: {{- $item | indent 1}} 
  {{- end}}
type: Opaque
